### ISSUE TITLE
BUG -- `numpy>2` raises `ValueError`.

### ISSUE THREAD

**Issue by it176131** [GraphBLAS/python-suitesparse-graphblas#131]
To recreate (using Python 3.12 on Windows):
```shell
$ py -3.12 -m venv env
$ source env/Scripts/activate
$ python -m pip install -U pip
$ pip install suitesparse-graphblas
$ python -c "import suitesparse_graphblas"
```

```python-traceback
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "~\env\Lib\site-packages\suitesparse_graphblas\__init__.py", line 18, in <module>
    from . import utils
  File "suitesparse_graphblas\\utils.pyx", line 1, in init suitesparse_graphblas.utils
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

Related: #130

**Comment by eriknw** [comment]
Thanks for the bug report!

It looks like #130 is a WIP to support NumPy 2, and the main thing that is needed is to rebuild wheels using NumPy 2:
https://github.com/GraphBLAS/python-suitesparse-graphblas/pull/130/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L9-R9

To get automated wheels working again, it looks like we need to do some updates for `cibuildwheel` as was also done in #128.

**Comment by alugowski** [comment]
> To get automated wheels working again, it looks like we need to do some updates for `cibuildwheel` as was also done in #128.

@eriknw #128 is ready for review.
